include: package:workiva_analysis_options/v2.recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - _site/**
    - test_fixtures/**
    - app/**
    - tools/analyzer_plugin/**
    - ddc_precompiled/**
  errors:
    # Workaround for https://github.com/dart-lang/sdk/issues/51087
    # TODO remove once we're no longer running CI on Dart 2.18
    part_of_different_library: ignore

    # Too noisy for over_react code / boilerplate
    always_declare_return_types: ignore
    avoid_types_on_closure_parameters: ignore
    prefer_mixin: ignore
    type_annotate_public_apis: ignore

    # Affects generated code
    unnecessary_this: ignore
    unused_field: ignore

    # Lints that have too many exceptions and provide limited value
    avoid_private_typedef_functions: ignore
    join_return_with_assignment: ignore

    # Fixing these would cause a lot of changes, and these lints don't provide too much value
    prefer_interpolation_to_compose_strings: ignore
    sort_unnamed_constructors_first: ignore
    unnecessary_lambdas: ignore

    # Fixing these would cause a lot of changes; clean up after null safety branch
    always_put_required_named_parameters_first: ignore
    avoid_function_literals_in_foreach_calls: ignore
    avoid_positional_boolean_parameters: ignore
    avoid_renaming_method_parameters: ignore
    directives_ordering: ignore
    file_names: ignore
    omit_local_variable_types: ignore
    overridden_fields: ignore
    prefer_asserts_in_initializer_lists: ignore
    prefer_final_in_for_each: ignore
    prefer_final_locals: ignore
    unnecessary_parenthesis: ignore
    unnecessary_string_interpolations: ignore

    # Maybe fix within null safety branch in follow-up PR?
    prefer_final_fields: ignore
    prefer_void_to_null: ignore
