analyzer:
  exclude:
    - integrate/**
    - _site/**
  strong-mode: true
  # Add this to your project `analysis_options.yaml` to enable the built_value
  # analyzer plugin. You should also add the top level `plugins` clause below.
  # The plugin surfaces generator errors in your IDE, with suggested fixes
  # where possible.
  plugins:
    over_react_analyzer_plugin


# Add this to your project analysis_options.yaml to enable the built_value
# analyzer plugin. You should also add the `plugins` clause under `analyzer`,
# above.
plugins:
  over_react_analyzer_plugin:
    enabled: true

linter:
  rules:
    - annotate_overrides
    - avoid_as
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - empty_constructor_bodies
    - hash_and_equals
    - library_names
    - library_prefixes
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
