include: package:pedantic/analysis_options.1.8.0.yaml

analyzer:
  exclude:
    - _site/**
    - test_fixtures/**
    - app/**
    - tools/analyzer_plugin/**
  errors:
    missing_required_param: error
    must_call_super: error
linter:
  rules:
    # -------------------
    # Pedantic
    # -------------------
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_relative_lib_imports: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    valid_regexps: true

    # -------------------
    # Other
    # -------------------
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_null_checks_in_equality_operators: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_types_on_closure_parameters: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    hash_and_equals: true
    implementation_imports: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    package_names: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_declarations: true
    prefer_constructors_over_static_methods: true
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_null_aware_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    test_types_in_equals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_statements: true
    unsafe_html: true
    use_function_type_syntax_for_parameters: true
    use_to_and_as_if_applicable: true
    void_checks: true
