builders:
  overReactBuilder:
    import: "package:over_react/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: dependents
    build_to: cache

  # Builder just for this package.
  _over_react_local_builder:
    import: "package:over_react/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".over_react.g.dart"]}
    auto_apply: none
    build_to: source

targets:
  $default:
    builders:
      over_react|_over_react_local_builder:
        enabled: true
        generate_for:
          include:
            - "lib/**"
            - "test/**"
            - "web/component1/**"
            # The Dart 2 only boilerplate does not analyze cleanly without a build so the generated files need to be
            # checked in.
            - "example/boilerplate_versions/dart2_only/**"
          exclude:
            # These tests analyze cleanly without a build so the generated files do not need to be checked in.
            - "test/over_react/component_declaration/builder_integration_tests/backwards_compatible/**"
            - "test/over_react/component_declaration/builder_integration_tests/new_boilerplate/**"
            # These test un-built base class behavior, and contain code that might look like declarations
            # and should definitely not be built
            - "test/over_react/component_declaration/builder_helpers_test.dart"
            - "test/over_react/component_declaration/component_base_test.dart"

      over_react|overReactBuilder:
        enabled: true
        generate_for:
          include:
            - "web/**"
            - "example/**"
            # These tests analyze cleanly without a build so the generated files do not need to be checked in.
            - "test/over_react/component_declaration/builder_integration_tests/backwards_compatible/**"
            - "test/over_react/component_declaration/builder_integration_tests/new_boilerplate/**"
          exclude:
            - "web/component1/**"
            # The Dart 2 only boilerplate does not analyze cleanly without a build so the generated files need to be
            # checked in.
            - "example/boilerplate_versions/dart2_only/**"

#      build_vm_compilers|entrypoint:
#        generate_for:
#          include:
#            - "test/vm_tests/**"

      # builder uses mirrors and will cause a build to fail when using build web compilers
      # vm tests require the use of mirrors
      build_web_compilers|ddc:
        generate_for:
          include:
            - "example/**"
            - "lib/**"
            - "test/**"
            - "web/**"
          exclude:
            - "lib/src/builder/**"

      build_web_compilers|entrypoint:
        generate_for:
          - "example/**.dart"
          - "test/*.browser_test.dart"
          - "web/**/index.dart"
        options:
          dart2js_args:
            - --no-minify
