builders:
  overReactBuilder:
    import: "package:over_react/src/builder/builder.dart"
    builder_factories: ["overReactBuilder"]
    build_extensions: {".dart" : [".overReactBuilder.g.dart"]}
    auto_apply: dependents 
    build_to: source 

targets:
  $default:
    sources:
#      include:
##        - "example/builder/**"
#        - "example/**"
#        - "lib/src/component/**"
      exclude:
        - ".dart_tool"
        - "lib/src/builder/**"
        - "lib/src/transformer/**"
#        - "test/over_react_builder_test.dart"
        - "test/component_files/**"
        - "test/gold_files/**"
        - "test/**"
    builders:
      built_value_generator|built_value:
        enabled: false
      built_redux|built_redux:
        enabled: false
      over_react|overReactBuilder:
        enabled: true
        generate_for:
#          - "example/**"
#          - "lib/src/**"
#          - "test/component_files/**"
#          - "example/builder/basic.dart"


