name: over_react__test__non_null_safe
publish_to: none
environment:
  # This test package specifically has an SDK constraint lower than null safety
  sdk: ">=2.11.0 <3.0.0"
dependencies:
  over_react:
    path: ../../../
dev_dependencies:
  build_runner: any
  # Pull in this package so that we can test builder generation for non-root packages.
  over_react__test__null_safe:
    path: ../null_safe

workiva:
  disable_core_checks: true

dependency_overrides:
  react:
    git:
      url: https://github.com/Workiva/react-dart.git
      ref: react-18-2-0-testing
  react_testing_library:
    git:
      url: https://github.com/Workiva/react_testing_library.git
      ref: r18
  dart_dev_workiva:
    git:
      url: https://github.com/Workiva/dart_dev_workiva.git
      ref: override-react-js-files-for-r18
