name: over_react_builder
version: 5.5.0
description: Builder and code generation for over_react components.
homepage: https://github.com/Workiva/over_react/
publish_to: none
environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: '>=5.13.0 <8.0.0'
  build: ^2.0.0
  collection: ^1.15.0
  dart_style: '>=2.0.0 <4.0.0'
  logging: ^1.0.0
  meta: ^1.16.0
  package_config: ^2.1.0
  pub_semver: ^2.0.0
  path: ^1.5.1
  source_span: ^1.4.1
  transformer_utils: ^0.2.6
  over_react:
    path: ../../

dev_dependencies:
  benchmark_harness: ^2.2.1
  build_resolvers: ^2.0.0
  build_runner: ^2.0.0
  build_test: '>=2.0.0 <4.0.0'
  build_web_compilers: '>=3.2.6 <5.0.0'
  glob: ^2.0.1
  io: ^1.0.0
  test: ^1.20.0
  workiva_analysis_options: ^1.4.0
  yaml: ^3.1.0
