name: over_react_analyzer_plugin
version: 0.1.0
description: Dart analyzer plugin for OverReact
homepage: https://github.com/greglittlefield-wf/git_playground/tree/over_react_analyzer_plugin/master
authors:
  - Greg Littlefield <greg.littlefield@workiva.com>
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  analyzer: '^0.39.10'
  analyzer_plugin: '^0.2.4'
  dart_dev: ^3.0.0
  over_react: ^3.5.3
  meta: ^1.1.6
  path: ^1.5.1
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.0.0
  build_vm_compilers: ^1.0.0
  test: ^1.0.0
  workiva_analysis_options: ^1.1.0
