analyzer:
  strong-mode: true
  plugins:
    over_react_analyzer_plugin_host

plugins:
  over_react_analyzer_plugin_host:
    enabled: true

linter:
  rules:
    - annotate_overrides
    - avoid_as
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - empty_constructor_bodies
    - hash_and_equals
    - library_names
    - library_prefixes
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - prefer_is_not_empty
    - slash_for_doc_comments
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
