name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_**'
    tags:
      - "**"
  pull_request:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  # Run as a separate job outside the Dart SDK matrix below,
  # since we can only emit a single SBOM.
  build:
    uses: Workiva/gha-dart-oss/.github/workflows/build.yaml@v0.1.11

  checks:
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.11
    with:
      additional-checks: |
        no_entrypoint_imports

  test_and_check_generated_files:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable ]
    steps:
      - uses: actions/checkout@v4
      - id: setup-dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - id: install
        name: Install dependencies
        run: dart pub get

      - name: Delete Dart-2-only files and update tests when running on Dart 3
        run: |
          DART_VERSION="${{ steps.setup-dart.outputs.dart-version }}"
          if [[ "$DART_VERSION" =~ ^3 ]]; then
            ./tool/delete_dart_2_only_files.sh
            ./tool/update_tests_for_dart_3.sh
          fi

      # Analyze before generated files are created to verify that component boilerplate analysis is "clean" without the need for building
      - name: Analyze example source (pre-build)
        run: |
          # Analyze lib to ensure public APIs don't depend on build-to-cache files,
          # which could cause analysis issues for consumers who haven't run a build yet.
          dart analyze lib
          dart analyze example/boilerplate_versions
        if: always() && steps.install.outcome == 'success'

      - id: build
        timeout-minutes: 6
        name: Build generated files / precompile DDC assets
        run: |
          dart run build_runner build --delete-conflicting-outputs -o ddc_precompiled
        if: always() && steps.install.outcome == 'success'

      - name: Verify that generated files are up-to-date
        run: |
          if [ ${{ matrix.sdk }} = '2.19.6' ]; then
            git diff --exit-code
          else
            # Don't check these generated files for other SDKs, since they may generate differently
            # due to different resolved dependencies.
            git diff --exit-code -- ":(exclude)test/over_react/component_declaration/redux_component_test/test_reducer.g.dart"
          fi
        if: always() && steps.install.outcome == 'success' && steps.install.build == 'success'

      # Analyze again after generated files are created to verify that those generated classes don't cause analysis errors
      - name: Analyze project source (post-build)
        run: dart analyze
        if: always() && steps.install.outcome == 'success' && steps.build.outcome == 'success'

      - name: Run tests (VM)
        # Can't use build_runner (which dart_dev uses if you depend on it) to run VM tests, since we get the error:
        #    Unable to spawn isolate: /…/build_runner_testRU6M77/.packages: Error: Problem in packages configuration file: Unexpected character
        run: |
          DART_VERSION="${{ steps.setup-dart.outputs.dart-version }}"
          TEST_ARGS=""
          if [[ "$DART_VERSION" =~ ^3 ]]; then
            TEST_ARGS="--preset=no-dart-2"
          fi
          dart test --preset vm $TEST_ARGS
        if: always() && steps.install.outcome == 'success' && steps.build.outcome == 'success'

      - name: Run tests (DDC)
        run: dart test --precompiled ddc_precompiled -P dartdevc
        if: always() && steps.install.outcome == 'success' && steps.build.outcome == 'success'
        timeout-minutes: 5

      - name: Run tests (dart2js)
        run: dart run dart_dev test --build-args="-r" -P dart2js
        if: always() && steps.install.outcome == 'success' && steps.build.outcome == 'success'
        timeout-minutes: 5

  validate_analyzer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable ]
        analyzer:
          - ^5.13.0 # This should match the lower bound
          - ^6.0.0
          - ^7.0.0
        exclude:
          # Analyzer 6+ only resolves in Dart 3
          - sdk: 2.19.6
            analyzer: ^6.0.0
          - sdk: 2.19.6
            analyzer: ^7.0.0

    steps:
      - uses: actions/checkout@v4
      - id: setup-dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Update analyzer constraint to ${{ matrix.analyzer }} and validate `dart pub get` can resolve
        id: resolve
        run: |
          dart tool/set_analyzer_constraint.dart "${{ matrix.analyzer }}"
          # Show the updated version constraint
          git diff pubspec.yaml
          dart pub get

      - name: Delete Dart-2-only files and update tests when running on Dart 3
        run: |
          DART_VERSION="${{ steps.setup-dart.outputs.dart-version }}"
          if [[ "$DART_VERSION" =~ ^3 ]]; then
            ./tool/delete_dart_2_only_files.sh
            ./tool/update_tests_for_dart_3.sh
          fi

      - name: Analyze package source
        run: dart analyze .

      - name: Verify builder runs without errors
        run: dart run build_runner build --build-filter='**.dart' --delete-conflicting-outputs

      - name: Run builder tests
        run: |
          DART_VERSION="${{ steps.setup-dart.outputs.dart-version }}"
          TEST_ARGS=""
          if [[ "$DART_VERSION" =~ ^3 ]]; then
            TEST_ARGS="--preset=no-dart-2"
          fi
          dart test --preset vm $TEST_ARGS -- test/vm_tests/builder

  analyzer_plugin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/analyzer_plugin
    strategy:
      fail-fast: false
      matrix:
        sdk: [ 2.19.6, stable ]
    steps:
      - uses: actions/checkout@v4
      - id: setup-dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Print Dart SDK version
        run: dart --version

      - id: link
        name: Override over_react dependency with local path
        run: cd ../.. && dart pub get && dart tool/travis_link_plugin_deps.dart

      - id: install
        name: Install dependencies
        run: dart pub get
        if: always() && steps.link.outcome == 'success'

      - name: Delete Dart-2-only files and update tests when running on Dart 3
        run: |
          DART_VERSION="${{ steps.setup-dart.outputs.dart-version }}"
          if [[ "$DART_VERSION" =~ ^3 ]]; then
            (cd ../.. && ./tool/delete_dart_2_only_files.sh && ./tool/update_tests_for_dart_3.sh)
          fi

      - name: Validate dependencies
        run: dart run dependency_validator
        if: always() && steps.install.outcome == 'success'

      - name: Analyze
        run: dart run dart_dev analyze
        if: always() && steps.install.outcome == 'success'

      - name: Verify formatting
        run: dart run dart_dev format --check
        if: always() && matrix.sdk == '2.7.2' && steps.install.outcome == 'success'

      - name: Run tests
        run: dart run dart_dev test
        if: always() && steps.install.outcome == 'success'
        timeout-minutes: 8

  testing-and-checks-complete:
    name: Testing and Checks Completed
    needs: [ build, checks, test_and_check_generated_files, validate_analyzer, analyzer_plugin ]
    if: ${{ !cancelled() && github.event_name == 'pull_request' || github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          if [ "${{ needs.checks.result }}" == "failure" ]; then
            echo "Some checks have failed. Please fix the issues and try again."
            exit 1
          fi
          echo 'All Testing and checks have completed.'
