name: CI

on:
  push:
    branches:
      - 'master'
      - 'test_consume_**'
  pull_request:
    branches:
      - '**'

jobs:
  dart:
    strategy:
      fail-fast: false
      matrix:
        # Can't run on `dev` (Dart 3) until we're fully null-safe.
        sdk: [ 2.18.7, 2.19.6 ]
    uses: ./.github/workflows/jobs.yml
    with:
      sdk: ${{ matrix.sdk }}