name: OSS Release

# Only run the publish workflow when the release has been published to Github.
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v0.2
        with:
          sdk: 2.18.7
      - name: Add pub token
        run: dart pub token add ${{ secrets.OSS_PUB_TOKEN }}
      - name: Publish Package
        run: dart pub publish