# https://dart.dev/tools/pub/automated-publishing#hardening-security-with-github-deployment-environments
name: OSS Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - 'oss-pub'

jobs:
  build-docs-and-pub:
    name: 'Publish to pub.dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.5.0
        with:
          sdk: 2.18.7
      - run: dart pub get
      - name: Install dartdoc
        run: dart pub global activate dartdoc
      - name: Generate API docs
        run: dartdoc
      - name: Add pub token
        run: dart pub token add ${{ secrets.OSS_PUB_TOKEN }}
      - name: Publish Package - Dry Run
        run: |
          # Prevent the analyzer plugin from the publish dry run
          echo "tools/" > .pubignore
          dart pub publish --dry-run
          # Ensure that the artifact is cleaned up so that we can publish the analyzer.
          rm .pubignore
      - name: Publish Package
        if: false
        run: dart pub publish -f